### PR TITLE
Add !default to variables definition

### PR DESCRIPTION
**Pull request by mwinandy**
see https://github.com/nobitagit/material-floating-button/issues/8 .

Must be forwarded to mbf variation.

### CODE REVIEW

**Comment by nobitagit** [comment]
Hey there, looks good to me, thanks for the pull request.

Just a couple of things before I merge, would you also be able to add a very brief documentation about it   in the Readme file? And if you like you should also add your name as a contributor in the package.json (something along [these lines](http://browsenpm.org/package.json)). I will then add the names of the other contributors to date.

Thanks again, cheers for now.

**Comment by mwinandy** [comment]
Done !

Comment if you want !

**Comment by nobitagit** [comment]
Tested the solution, works like a charm.
Will probably edit a tiny bit the readme part, also because I will remove `_customise.scss` entirely, as your suggested method is much cleaner.

**Comment by mwinandy** [comment]
Okay, I prefer leave this choice to you.

**Comment by nobitagit** [comment]
:thumbsup:
Merged, thank you very much!

**Pull request merged**
